package com.example.githubusers.core.dummy

// GithubAPIが 60件/h の制限があったので、開発用にダミーのレスポンスを用意

/**
 * ユーザーの一覧を取得する のレスポンス
 *
 * https://docs.github.com/en/rest/users/users#list-users
 */
const val usersJsonString = """{users: [
    {
        "login": "yuki-kamikita",
        "id": 35297494,
        "node_id": "MDQ6VXNlcjM1Mjk3NDk0",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297494?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/yuki-kamikita",
        "html_url": "https://github.com/yuki-kamikita",
        "followers_url": "https://api.github.com/users/yuki-kamikita/followers",
        "following_url": "https://api.github.com/users/yuki-kamikita/following{/other_user}",
        "gists_url": "https://api.github.com/users/yuki-kamikita/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/yuki-kamikita/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yuki-kamikita/subscriptions",
        "organizations_url": "https://api.github.com/users/yuki-kamikita/orgs",
        "repos_url": "https://api.github.com/users/yuki-kamikita/repos",
        "events_url": "https://api.github.com/users/yuki-kamikita/events{/privacy}",
        "received_events_url": "https://api.github.com/users/yuki-kamikita/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "swarm21",
        "id": 35297495,
        "node_id": "MDQ6VXNlcjM1Mjk3NDk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297495?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/swarm21",
        "html_url": "https://github.com/swarm21",
        "followers_url": "https://api.github.com/users/swarm21/followers",
        "following_url": "https://api.github.com/users/swarm21/following{/other_user}",
        "gists_url": "https://api.github.com/users/swarm21/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/swarm21/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/swarm21/subscriptions",
        "organizations_url": "https://api.github.com/users/swarm21/orgs",
        "repos_url": "https://api.github.com/users/swarm21/repos",
        "events_url": "https://api.github.com/users/swarm21/events{/privacy}",
        "received_events_url": "https://api.github.com/users/swarm21/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "pta592",
        "id": 35297496,
        "node_id": "MDQ6VXNlcjM1Mjk3NDk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297496?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pta592",
        "html_url": "https://github.com/pta592",
        "followers_url": "https://api.github.com/users/pta592/followers",
        "following_url": "https://api.github.com/users/pta592/following{/other_user}",
        "gists_url": "https://api.github.com/users/pta592/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pta592/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pta592/subscriptions",
        "organizations_url": "https://api.github.com/users/pta592/orgs",
        "repos_url": "https://api.github.com/users/pta592/repos",
        "events_url": "https://api.github.com/users/pta592/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pta592/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "ediededi",
        "id": 35297497,
        "node_id": "MDQ6VXNlcjM1Mjk3NDk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297497?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ediededi",
        "html_url": "https://github.com/ediededi",
        "followers_url": "https://api.github.com/users/ediededi/followers",
        "following_url": "https://api.github.com/users/ediededi/following{/other_user}",
        "gists_url": "https://api.github.com/users/ediededi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ediededi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ediededi/subscriptions",
        "organizations_url": "https://api.github.com/users/ediededi/orgs",
        "repos_url": "https://api.github.com/users/ediededi/repos",
        "events_url": "https://api.github.com/users/ediededi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ediededi/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "DMHotWater",
        "id": 35297498,
        "node_id": "MDQ6VXNlcjM1Mjk3NDk4",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297498?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/DMHotWater",
        "html_url": "https://github.com/DMHotWater",
        "followers_url": "https://api.github.com/users/DMHotWater/followers",
        "following_url": "https://api.github.com/users/DMHotWater/following{/other_user}",
        "gists_url": "https://api.github.com/users/DMHotWater/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/DMHotWater/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/DMHotWater/subscriptions",
        "organizations_url": "https://api.github.com/users/DMHotWater/orgs",
        "repos_url": "https://api.github.com/users/DMHotWater/repos",
        "events_url": "https://api.github.com/users/DMHotWater/events{/privacy}",
        "received_events_url": "https://api.github.com/users/DMHotWater/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "ColinWeightman",
        "id": 35297500,
        "node_id": "MDQ6VXNlcjM1Mjk3NTAw",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297500?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ColinWeightman",
        "html_url": "https://github.com/ColinWeightman",
        "followers_url": "https://api.github.com/users/ColinWeightman/followers",
        "following_url": "https://api.github.com/users/ColinWeightman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ColinWeightman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ColinWeightman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ColinWeightman/subscriptions",
        "organizations_url": "https://api.github.com/users/ColinWeightman/orgs",
        "repos_url": "https://api.github.com/users/ColinWeightman/repos",
        "events_url": "https://api.github.com/users/ColinWeightman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ColinWeightman/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "lupitarendon501",
        "id": 35297501,
        "node_id": "MDQ6VXNlcjM1Mjk3NTAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297501?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lupitarendon501",
        "html_url": "https://github.com/lupitarendon501",
        "followers_url": "https://api.github.com/users/lupitarendon501/followers",
        "following_url": "https://api.github.com/users/lupitarendon501/following{/other_user}",
        "gists_url": "https://api.github.com/users/lupitarendon501/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lupitarendon501/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lupitarendon501/subscriptions",
        "organizations_url": "https://api.github.com/users/lupitarendon501/orgs",
        "repos_url": "https://api.github.com/users/lupitarendon501/repos",
        "events_url": "https://api.github.com/users/lupitarendon501/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lupitarendon501/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jiratkhan",
        "id": 35297502,
        "node_id": "MDQ6VXNlcjM1Mjk3NTAy",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297502?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jiratkhan",
        "html_url": "https://github.com/jiratkhan",
        "followers_url": "https://api.github.com/users/jiratkhan/followers",
        "following_url": "https://api.github.com/users/jiratkhan/following{/other_user}",
        "gists_url": "https://api.github.com/users/jiratkhan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jiratkhan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jiratkhan/subscriptions",
        "organizations_url": "https://api.github.com/users/jiratkhan/orgs",
        "repos_url": "https://api.github.com/users/jiratkhan/repos",
        "events_url": "https://api.github.com/users/jiratkhan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jiratkhan/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "gorditogr",
        "id": 35297503,
        "node_id": "MDQ6VXNlcjM1Mjk3NTAz",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gorditogr",
        "html_url": "https://github.com/gorditogr",
        "followers_url": "https://api.github.com/users/gorditogr/followers",
        "following_url": "https://api.github.com/users/gorditogr/following{/other_user}",
        "gists_url": "https://api.github.com/users/gorditogr/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gorditogr/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gorditogr/subscriptions",
        "organizations_url": "https://api.github.com/users/gorditogr/orgs",
        "repos_url": "https://api.github.com/users/gorditogr/repos",
        "events_url": "https://api.github.com/users/gorditogr/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gorditogr/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "maxon-works",
        "id": 35297504,
        "node_id": "MDQ6VXNlcjM1Mjk3NTA0",
        "avatar_url": "https://avatars.githubusercontent.com/u/35297504?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maxon-works",
        "html_url": "https://github.com/maxon-works",
        "followers_url": "https://api.github.com/users/maxon-works/followers",
        "following_url": "https://api.github.com/users/maxon-works/following{/other_user}",
        "gists_url": "https://api.github.com/users/maxon-works/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/maxon-works/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/maxon-works/subscriptions",
        "organizations_url": "https://api.github.com/users/maxon-works/orgs",
        "repos_url": "https://api.github.com/users/maxon-works/repos",
        "events_url": "https://api.github.com/users/maxon-works/events{/privacy}",
        "received_events_url": "https://api.github.com/users/maxon-works/received_events",
        "type": "User",
        "site_admin": false
    }
]}"""

/**
 * ユーザーを取得する のレスポンス
 *
 * https://docs.github.com/en/rest/users/users#get-a-user
 */
const val userJsonString = """{
    "login": "yuki-kamikita",
    "id": 35297494,
    "node_id": "MDQ6VXNlcjM1Mjk3NDk0",
    "avatar_url": "https://avatars.githubusercontent.com/u/35297494?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yuki-kamikita",
    "html_url": "https://github.com/yuki-kamikita",
    "followers_url": "https://api.github.com/users/yuki-kamikita/followers",
    "following_url": "https://api.github.com/users/yuki-kamikita/following{/other_user}",
    "gists_url": "https://api.github.com/users/yuki-kamikita/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yuki-kamikita/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yuki-kamikita/subscriptions",
    "organizations_url": "https://api.github.com/users/yuki-kamikita/orgs",
    "repos_url": "https://api.github.com/users/yuki-kamikita/repos",
    "events_url": "https://api.github.com/users/yuki-kamikita/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yuki-kamikita/received_events",
    "type": "User",
    "site_admin": false,
    "name": "yuki",
    "company": "Japan",
    "blog": "https://akaiyukiusagi.com",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "こんにちは",
    "twitter_username": "yuki_kamikita",
    "public_repos": 45,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2018-01-10T12:23:16Z",
    "updated_at": "2022-09-20T09:37:11Z"
}"""